keys:
    # Recovery key - stored in password manager
    - &recovery age1r5y20hy0mwx5f628ykxgk3lquphegglew0ealsmncwzfaj40zqaqeff6n5

    # Per-host keys (generate with: ./scripts/sops-init-host.sh)
    - &io age15yvj4g487qq353sqv3l7cp3h7gmwev5vpdzadmrsytcw8530rp8qm5smfn
    - &janus age12cscjc5zfv6c74v3es2kj83qxdtpuy8upzycwphyrv4adlej5slsf9ya4g
    - &leda age1d3zx9zznu3pp2sudd8s3as7jzfnhu3uczm0sklrmhuv7a7hvv54q6n4hk9

creation_rules:
    # Shared secrets - accessible by all hosts
    -   path_regex: secrets/shared\.yaml$
        key_groups:
            -   age:
                    - *recovery
                    - *io
                    - *janus
                    - *leda

    # Per-host secrets
    -   path_regex: secrets/io\.yaml$
        key_groups:
            -   age:
                    - *recovery
                    - *io

    -   path_regex: secrets/janus\.yaml$
        key_groups:
            -   age:
                    - *recovery
                    - *janus

    -   path_regex: secrets/leda\.yaml$
        key_groups:
            -   age:
                    - *recovery
                    - *leda
